export const typeBorderColors = {
  normal: "border-zinc-400",
  fire: "border-orange-500",
  water: "border-blue-500",
  electric: "border-yellow-400",
  grass: "border-green-500",
  ice: "border-cyan-400",
  fighting: "border-red-700",
  poison: "border-purple-600",
  ground: "border-amber-600",
  flying: "border-sky-400",
  psychic: "border-pink-500",
  bug: "border-lime-600",
  rock: "border-stone-600",
  ghost: "border-indigo-700",
  dragon: "border-indigo-500",
  dark: "border-neutral-800",
  steel: "border-slate-400",
  fairy: "border-rose-300",
};
